# Generated by Django 4.1.5 on 2023-01-20 01:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ownerName', models.CharField(max_length=100)),
                ('characterName', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('className', models.CharField(max_length=100)),
                ('armorClass', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('level', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('totalhp', models.IntegerField()),
                ('wisdom', models.IntegerField()),
            ],
        ),
    ]
