# Generated by Django 4.1.5 on 2023-01-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastertools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayersModel',
            new_name='Players',
        ),
    ]
