# Generated by Django 4.1.5 on 2023-01-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastertools', '0002_rename_playersmodel_players'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
    ]
