# Generated by Django 4.1.5 on 2023-01-21 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mastertools', '0003_rename_players_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('history', models.CharField(max_length=200)),
            ],
        ),
    ]
